name: rispar_project
description: Rispar Acquisition Simulation

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

vars: 
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner build`
  runner_clean: flutter pub run build_runner clean`
  runner_conflits: flutter pub run build_runner build --delete-conflicting-outputs`

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  dio: ^4.0.0
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  mobx: ^2.0.4
  flutter_mobx: ^2.0.0
  modular_codegen: ^3.0.0
  mobx_codegen: ^2.0.1+3
  flutter_svg: ^1.1.0
  email_validator: ^2.0.0-nullsafety
  step_progress_indicator: ^1.0.2
  flutter_dotenv: ^5.0.2
  alert: ^2.0.1
  screen_size_test: ^1.0.2+3

dev_dependencies:
  flutter_native_splash: ^2.2.3+1
  flutter_test:
    sdk: flutter
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  build_runner: ^1.10.1
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
